spring.application.name=demo
server.port=8080
app.greeting=Hello,
#spring.profiles.active=dev

#actuator
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true
info.app.name=demo
info.app.description=A First Spring Boot Demo